language: php

sudo: false

php:
  - '7.2'
  - '7.3'
  - '7.4'

cache:
    directories:
        - vendor

install:
    # Install dependencies
    - composer self-update
    - composer install --prefer-dist

script:
    # Run tests
    - bin/phpunit

after_failure:
    # Display error logs
    - cat /var/log/php_errors.log
